version: "3.4"
services:


  vpn:
    cap_add: 
      - NET_ADMIN
    volumes: 
      - '${ROOT}/transmission:/data'
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - NORDVPN_COUNTRY=IT 
      - NORDVPN_CATEGORY=legacy_p2p 
      - LOCAL_NETWORK=192.168.0.0/16
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
      - '8112:8112'
    image: haugene/transmission-openvpn

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files


  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${EXTERNAL_HDD}/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${EXTERNAL_HDD}/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder

#  plex-server:
#    container_name: plex-server
#    image: plexinc/pms-docker:latest
#    restart: unless-stopped
#    environment:
#      - TZ=${TZ} # timezone, defined in .env
#    network_mode: host
#    volumes:
#      - ${ROOT}/config/plex/db:/config # plex database
#      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
#      - ${EXTERNAL_HDD}:/data # media library

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${EXTERNAL_HDD}/movies:/movies # movies folder
      - ${EXTERNAL_HDD}/tv:/tv # tv shows folder
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
    ports:
      - 9983:80
      - 81:8989
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ${ROOT}/config/tautulli:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
      
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/readarr:/config
      - ${EXTERNAL_HDD}/books:/books # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8787:8787
    restart: unless-stopped
    
    
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ${ROOT}/config/lazylibrarian:/config
      - ${ROOT}/downloads:/downloads # download folder
      - ${EXTERNAL_HDD}/books:/books # tv shows folder
